[project]
name = "playwright-simple-scraper"
version = "0.1.0"
description = "A simple Playwright-based scraper that returns List[str]"
authors = [
    { name = "elecbrandy", email = "elecbrandy@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "playwright>=1.44",
    "nest_asyncio>=1.5.6"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
