name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install -U pip
          python -m pip install build

      # 패키지와 dev 의존성 먼저 설치 (pytest 포함)
      - name: Install package (dev)
        run: |
          python -m pip install ".[dev]"

      # 패키지 설치 이후 브라우저/OS deps 설치
      - name: Install Playwright browsers (and OS deps)
        run: |
          python -m pip install playwright
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Verify installed browsers
        run: ls -l /home/runner/.cache/ms-playwright/ || true

      - name: Run tests
        run: pytest -q

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
