name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      # headless_shell 강제 방지 + 런치 채널 지정
      PW_CHROMIUM_USE_HEADLESS_SHELL: "0"
      PLAYWRIGHT_CHROMIUM_USE_HEADLESS_SHELL: "0"
      PW_CHANNEL: "chrome"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install -U pip
          python -m pip install build

      - name: Install package (dev)
        run: |
          python -m pip install ".[dev]"

      - name: Install Playwright browsers (Chrome channel, with OS deps)
        run: |
          python -m pip install playwright
          python -m playwright install --with-deps chrome
          python -m playwright --version
          ls -R /home/runner/.cache/ms-playwright/ || true

      - name: Smoke check: launch Chrome channel
        run: |
          python - <<'PY'
          import asyncio
          from playwright.async_api import async_playwright
          async def main():
              async with async_playwright() as pw:
                  b = await pw.chromium.launch(channel="chrome", headless=True, args=["--no-sandbox"])
                  print("LAUNCHED:", await b.version())
                  await b.close()
          asyncio.run(main())
          PY

      - name: Run tests
        run: pytest -q

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
