name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}   # 수동 실행도 가능하게(디버그용)

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install -U pip
          python -m pip install build

      - name: Install Playwright browsers (and OS deps)
        run: |
          python -m pip install playwright
          python -m playwright install chromium-headless-shell
          python -m playwright install-deps chromium-headless-shell

      - name: Run tests
        run: |
          python -m pip install .[dev]
          pytest -q              # e2e 포함 (headless=True라 CI에서 동작)

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
